-- =====================================================
-- 留言板项目 - 数据库 Schema
-- 执行方式：Supabase -> SQL Editor -> New Query -> 粘贴全部 -> Run
-- =====================================================

-- 1. 扩展 uuid-ossp（如果尚未启用）
create extension if not exists "uuid-ossp";

-- =====================================================
-- 2. 创建 profiles 表（扩展 auth.users）
-- =====================================================
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username varchar(50) unique,
  avatar_url text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

-- profiles 策略：所有人可读，仅本人可写
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile." on public.profiles;
create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on public.profiles;
create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- =====================================================
-- 3. 创建 messages 表
-- =====================================================
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  content text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.messages enable row level security;

-- messages 策略：所有人可读
drop policy if exists "Messages are viewable by everyone." on public.messages;
create policy "Messages are viewable by everyone."
  on public.messages for select
  using ( true );

-- 登录用户可插入
drop policy if exists "Authenticated users can create messages." on public.messages;
create policy "Authenticated users can create messages."
  on public.messages for insert
  with check ( auth.role() = 'authenticated' );

-- 仅本人可更新
drop policy if exists "Users can update their own messages." on public.messages;
create policy "Users can update their own messages."
  on public.messages for update
  using ( auth.uid() = user_id );

-- 仅本人可删除
drop policy if exists "Users can delete their own messages." on public.messages;
create policy "Users can delete their own messages."
  on public.messages for delete
  using ( auth.uid() = user_id );

-- =====================================================
-- 4. 自动更新 updated_at 的触发器
-- =====================================================
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_messages_updated_at on public.messages;
create trigger on_messages_updated_at
  before update on public.messages
  for each row execute function public.handle_updated_at();

-- =====================================================
-- 5. 新用户注册时自动创建 profile 的 trigger function
-- =====================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  v_username text;
  v_avatar text;
begin
  -- 优先从 raw_user_meta_data 中提取 GitHub 信息
  v_username := coalesce(
    new.raw_user_meta_data ->> 'user_name',
    new.raw_user_meta_data ->> 'preferred_username',
    split_part(new.email, '@', 1),
    'user_' || substr(new.id::text, 1, 8)
  );

  v_avatar := coalesce(
    new.raw_user_meta_data ->> 'avatar_url',
    new.raw_user_meta_data ->> 'picture'
  );

  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    v_username,
    v_avatar
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

-- trigger 在 auth.users 上
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
